# Generated by Django 4.1.4 on 2023-07-13 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exchange', '0003_books_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0003_profile_fio'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritesUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Exchange.books')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
