# Generated by Django 4.1.4 on 2023-07-11 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('one_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange', to='Exchange.books')),
                ('two_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='two_book', to='Exchange.books')),
            ],
        ),
    ]
