# Generated by Django 4.1.4 on 2023-07-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exchange', '0002_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='avatar',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
