# Generated by Django 4.1.4 on 2023-07-13 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exchange', '0003_books_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='date',
        ),
    ]
