# Generated by Django 4.1.4 on 2023-07-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exchange', '0004_remove_exchange_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='avatar',
            field=models.ImageField(upload_to='media/book/'),
        ),
    ]
